// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Applicazione {
	/**
	 * 
	 */
	public String tipoAbbondamento;
	/**
	 * 
	 */
	public Cliente clienti;
	/**
	 * 
	 */
	public Dipendente dipendente;

	/**
	 * 
	 */
	public void verificaDisponibilitàMacchinario() {
	}

	/**
	 * 
	 */
	public void verificaArmadiettiliberi() {
	}

	/**
	 * 
	 */
	public void prenotaConsulenza() {
	}
}
