// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Abbonamento {
	/**
	 * 
	 */
	public EDate scadenza;
	/**
	 * 
	 */
	public Spogliatoio spogliatoio;
	/**
	 * 
	 */
	public String idAbbonamento;
	/**
	 * 
	 */
	public int idCliente;
	/**
	 * 
	 */
	public String fasciaOrariaConsentita;
	/**
	 * 
	 */
	public int prezzo;

	/**
	 * 
	 */
	public void rinnova() {
	}

	/**
	 * 
	 */
	public void sospendi() {
	}
}
