// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class DB_service implements Interface94 {
	/**
	 * 
	 */
	public undef Port1;
}
