// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class IstruttoreCorso extends Dipendente {
	/**
	 * 
	 */
	public String tipoCorsoInsegnato;

	/**
	 * 
	 * @return 
	 * @param cliente 
	 */
	public Corso consigliaCorso(Cliente cliente) {
	}
}
