// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Macchinario {
	/**
	 * 
	 */
	public String marca;
	/**
	 * 
	 */
	public boolean occupato;
	/**
	 * 
	 */
	public int capacitàCarico;
	/**
	 * 
	 */
	public String nome;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupato() {
	}
}
