// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Spogliatoio {
	/**
	 * 
	 */
	public int numArmadietti;
	/**
	 * 
	 */
	public int numDocce;
	/**
	 * 
	 */
	public int numArmadiettiLiberi;

	/**
	 * 
	 */
	public void assegnaArmadietto() {
	}

	/**
	 * 
	 */
	public void liberaArmadietto() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean verficaArmadiettiLiberi() {
	}
}
