// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class abbonamentoCompleto extends Abbonamento {
	/**
	 * 
	 */
	public Sala sala;
	/**
	 * 
	 */
	public int sogliaSconto;
}
