// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Corso {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public TipoCorso tipo;
	/**
	 * 
	 */
	public String durata;
	/**
	 * 
	 */
	public String idCorso;
	/**
	 * 
	 */
	public boolean richiedePrenotazione;
	/**
	 * 
	 */
	public IstruttoreCorso istruttorecorso;
	/**
	 * 
	 */
	public IstruttoreCorso istruttore;
	/**
	 * 
	 */
	public Cliente partecipanti;
	/**
	 * 
	 */
	public TipoCorso tipocorso;

	/**
	 * 
	 */
	public void aggiungiPartecipante() {
	}

	/**
	 * 
	 */
	public void rimuoviPartecipante() {
	}
}
