// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Gestione_abbonamenti implements IfornisceAbbonamento, Interface99 {
	/**
	 * 
	 */
	public undef Port1;
}
