// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public enum TipoCorso {
	/**
	 * 
	 */
	ACQUAGYMACQUAGYM,
	/**
	 * 
	 */
	PILATES,
	/**
	 * 
	 */
	SPINNING;
}
