// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class UI_utente implements IfornisceInterfUtenete {
	/**
	 * 
	 */
	public undef Port1;
}
