// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Gestione_corsi/sale/pt implements IfornisceCorsi,Interface88
{
				/**
				 * 
				 */
				public undef ;
}
