// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Gestione_prenotazioni/check-in implements IforniscePrenotazione
 {
				/**
				 * 
				 */
				public undef ;
}
