// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class IstruttoreCorso extends Dipendente {
	/**
	 * 
	 */
	public String tipoCorsoInsegnato;
	public Corso corso;

	/**
	 * 
	 * @return 
	 * @param cliente 
	 */
	public Corso consigliaCorso(Cliente cliente) {
		return corso ;
	}
}
